# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Desktop Distribution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout my repository
      uses: actions/checkout@v3

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: 'gradle'

    - name: Package Distribution
      run: |
        ./gradlew composeApp:packageDistributionForCurrentOS

    - name: Upload the Build Artifact (macos)
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-artifact@v3.1.1
      with:
          name: distribution
          path: composeApp/build/compose/binaries/main/dmg/*.dmg

    - name: Upload the Build Artifact (windows)
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-artifact@v3.1.1
      with:
        name: distribution
        path: composeApp/build/compose/binaries/main/msi/*.msi

    - name: Upload the Build Artifact (linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v3.1.1
      with:
        name: distribution
        path: composeApp/build/compose/binaries/main/deb/*.deb
